apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-backend
  namespace: sample-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-backend
  template:
    metadata:
      labels:
        app: sample-backend
    spec:
      containers:
        - name: sample-backend
          image: harbor.local:443/library/sample-backend:4
          ports:
            - containerPort: 3000
